In [36]:
# import necessary libraries
import pandas as pd

In [37]:
# load data
movies = pd.read_csv('movie.csv', encoding='latin1')
movies.head()

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
0,,NaN,NaN,Drama,NaN,NaN,J.S. Randhawa,Manmauji,Birbal,Rajendra Bhatia
1,#Gadhvi (He thought he was Gandhi),-2019.0,109 min,Drama,7.0,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid
2,#Homecoming,-2021.0,90 min,"Drama, Musical",NaN,NaN,Soumyajit Majumdar,Sayani Gupta,Plabita Borthakur,Roy Angana
3,#Yaaram,-2019.0,110 min,"Comedy, Romance",4.4,35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor
4,...And Once Again,-2010.0,105 min,Drama,NaN,NaN,Amol Palekar,Rajat Kapoor,Rituparna Sengupta,Antara Mali

In [38]:
# NA values
movies.isna()

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
0,False,True,True,False,True,True,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,True,True,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
15504,False,False,True,False,False,False,False,False,False,False
15505,False,False,False,False,False,False,False,False,False,False
15506,False,False,True,False,True,True,False,False,True,True
15507,False,False,True,False,True,True,True,True,True,True
15508,False,False,False,False,False,False,False,False,False,False

In [39]:
# handling missing values
data = movies.dropna(subset=['Year','Duration','Genre','Rating','Votes','Director','Actor 1','Actor 2','Actor 3'])
data

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
1,#Gadhvi (He thought he was Gandhi),-2019.0,109 min,Drama,7.0,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid
3,#Yaaram,-2019.0,110 min,"Comedy, Romance",4.4,35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor
5,...Aur Pyaar Ho Gaya,-1997.0,147 min,"Comedy, Drama, Musical",4.7,827,Rahul Rawail,Bobby Deol,Aishwarya Rai Bachchan,Shammi Kapoor
6,...Yahaan,-2005.0,142 min,"Drama, Romance, War",7.4,"1,086",Shoojit Sircar,Jimmy Sheirgill,Minissha Lamba,Yashpal Sharma
8,?: A Question Mark,-2012.0,82 min,"Horror, Mystery, Thriller",5.6,326,Allyson Patel,Yash Dave,Muntazir Ahmad,Kiran Bhatia
...,...,...,...,...,...,...,...,...,...,...
15493,Zubaan,-2015.0,115 min,Drama,6.1,408,Mozez Singh,Vicky Kaushal,Sarah Jane Dias,Raaghavv Chanana
15494,Zubeidaa,-2001.0,153 min,"Biography, Drama, History",6.2,"1,496",Shyam Benegal,Karisma Kapoor,Rekha,Manoj Bajpayee
15503,Zulm Ki Zanjeer,-1989.0,125 min,"Action, Crime, Drama",5.8,44,S.P. Muthuraman,Chiranjeevi,Jayamalini,Rajinikanth
15505,Zulmi,-1999.0,129 min,"Action, Drama",4.5,655,Kuku Kohli,Akshay Kumar,Twinkle Khanna,Aruna Irani
15508,Zulm-O-Sitam,-1998.0,130 min,"Action, Drama",6.2,20,K.C. Bokadia,Dharmendra,Jaya Prada,Arjun Sarja

In [40]:
# checking if new data have missing values
data.isna()

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
1,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
15493,False,False,False,False,False,False,False,False,False,False
15494,False,False,False,False,False,False,False,False,False,False
15503,False,False,False,False,False,False,False,False,False,False
15505,False,False,False,False,False,False,False,False,False,False
15508,False,False,False,False,False,False,False,False,False,False

In [41]:
# label encoder
from sklearn.preprocessing import LabelEncoder
for col in ['Genre','Director','Actor 1','Actor 2','Actor 3']:
    data.loc[:,col] = LabelEncoder().fit_transform(data[col])

data.loc[:,'Duration'] = data['Duration'].astype(str).str.replace(' min','').astype(float)

data = data.copy()
data.loc[:,'Year'] = pd.to_numeric(data['Year'].astype(str).str.extract(r'(\d{4})')[0], errors='coerce')

In [42]:
data

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
1,#Gadhvi (He thought he was Gandhi),2019.0,109.0,229,7.0,8,629,1352,2272,319
3,#Yaaram,2019.0,110.0,184,4.4,35,1335,1198,719,2148
5,...Aur Pyaar Ho Gaya,1997.0,147.0,157,4.7,827,1530,378,75,2045
6,...Yahaan,2005.0,142.0,289,7.4,"1,086",2044,692,1112,2524
8,?: A Question Mark,2012.0,82.0,320,5.6,326,135,1934,1175,1013
...,...,...,...,...,...,...,...,...,...,...
15493,Zubaan,2015.0,115.0,229,6.1,408,1223,1861,1801,1615
15494,Zubeidaa,2001.0,153.0,133,6.2,"1,496",2059,763,1619,1184
15503,Zulm Ki Zanjeer,1989.0,125.0,28,5.8,44,1793,406,754,1685
15505,Zulmi,1999.0,129.0,38,4.5,655,1025,112,2164,314
15508,Zulm-O-Sitam,1998.0,130.0,38,6.2,20,895,468,753,303

In [43]:
# initialising predictor and response variables
x = data.drop(['Name','Rating'],axis=1)
y = data.Rating

In [44]:
# training and testing sets
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [45]:
# model building
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [51]:
# Clean the data by removing commas and converting to float
x_train = x_train.replace(',', '', regex=True).infer_objects(copy=False).astype(float)
y_train = y_train.replace(',', '', regex=True).infer_objects(copy=False).astype(float)
x_test = x_test.replace(',', '', regex=True).infer_objects(copy=False).astype(float)
y_test = y_test.replace(',', '', regex=True).infer_objects(copy=False).astype(float)


# fitting the data to the model
model.fit(x_train,y_train)

LinearRegression()

In [47]:
# prediction
y_pred = model.predict(x_test)

In [48]:
# computing error
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test,y_pred)
print('Mean Absolute Error:',mae)

Mean Absolute Error: 1.049562505489381

In [49]:
# resultant matrix
import numpy as np
result_matrix = np.column_stack((y_test, y_pred))
print('  True         Predicted')
print(result_matrix)

  True         Predicted
[[6.         5.63033377]
 [2.4        5.84119076]
 [3.8        5.93058305]
 ...
 [4.8        5.60661345]
 [6.7        5.62132497]
 [6.6        6.54181763]]